import { DataTable } from "@/src/components/data-table"
import { SectionCards } from "@/src/components/section-cards"
import data from "./data.json"
import ChartAreaInteractive from "@/src/components/chart-area-interactive"
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};
export default function Page() {
  return (
    <div className="flex flex-col gap-4 py-4 md:gap-6 md:py-6">
      <SectionCards />
        <div className="px-4 lg:px-6">
          <ChartAreaInteractive />
        </div>
      <DataTable data={data} />
    </div>
  )
}
