import { DataTable } from "@/src/components/dashboard/data-table";
import { SectionCards } from "@/src/components/dashboard/section-cards";
import ChartAreaInteractive from "@/src/components/dashboard/chart-area-interactive";
import data from "./data.json";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div className="flex flex-col gap-4 py-4 md:gap-6 md:py-6">
      <SectionCards />
      <div className="px-4 lg:px-6">
        <ChartAreaInteractive />
      </div>
      <DataTable data={data} />
    </div>
  );
}
